name: glue-jupyter
channels:
  - conda-forge
dependencies:
  - glue-core
  - pip
  - jupyterlab >=0.32
  - ipywidgets
# these are for now installed from git master in postBuild
#  - bqplot
#  - ipyvolume
  - ipympl
